### ISSUE TITLE
[ERROR] output in wallet but not in ord server:xxxxxxxxxx

### ISSUE THREAD

**Issue by ohxiyu** [ordinals/ord#3570] opened 2024-04-17 03:35 UTC
When operating the command, it prompts output in wallet but not in ord server: transaction hash.
I suspect it is caused by a version bug.

Configuration file

no_index_inscription: true
index_runes: true
index_cache_size: 26000000000
chain: testnet

Solution
Modify configuration file

index_runes: true
index_cache_size: 26000000000
first_inscription_height: 2580000
chain: testnet

Delete the index database and re-index

**Comment by cryptoni9n** [comment] 2024-04-17 05:10
Dupe of #3560 

3rd case I've seen today and each has the no_index_inscriotion set to true instead of false

**Comment by vfeihuang** [comment] 2024-04-18 07:00
There is still an error 
config :

```
index_runes: true
index_cache_size: 6800000000

bitcoin_data_dir: H:\bitcoin_data
bitcoin_rpc_username: bitcoin
bitcoin_rpc_password: bitcoin2024KL
data_dir: H:\ord-data
```

version: 0.18.2  and  bitcoin core version 27.0   on windows.
I tried to delete index.redb and re-index already .

**Comment by mustvlad** [comment] 2024-04-18 23:16
Same for me with `ord 0.18.2`: 

```
chain: testnet
no_index_inscriptions: true
index_runes: true
index_cache_size: 8858365080
```

**Comment by cryptoni9n** [comment] 2024-04-19 00:39
> There is still an error config :
> 
> ```
> index_runes: true
> index_cache_size: 6800000000
> 
> bitcoin_data_dir: H:\bitcoin_data
> bitcoin_rpc_username: bitcoin
> bitcoin_rpc_password: bitcoin2024KL
> data_dir: H:\ord-data
> ```
> 
> version: 0.18.2 and bitcoin core version 27.0 on windows. I tried to delete index.redb and re-index already .

run `ord --data-dir <DATA_DIR> settings' and paste the results here please.

**Comment by cryptoni9n** [comment] 2024-04-19 00:40
> Same for me with `ord 0.18.2` on linux:
> 
> ```
> chain: testnet
> no_index_inscriptions: true
> index_runes: true
> index_cache_size: 8858365080
> ```

run `ord --data-dir <DATA_DIR> settings` and paste the results here please.

**Comment by xinzhongyouhai** [comment] 2024-04-19 11:10
> > 我`ord 0.18.2`在 Linux 上也一样：
> > ```
> > chain: testnet
> > no_index_inscriptions: true
> > index_runes: true
> > index_cache_size: 8858365080
> > ```
> 
> 请运行`ord --data-dir <DATA_DIR> settings`并将结果粘贴到此处。

我在signet输出结果是这个：
D:\ord\target\release> .\ord.exe --data-dir C:\Users\Administrator\AppData\Roaming\ord\signet settings
{
  "bitcoin_data_dir": "C:\\Users\\Administrator\\AppData\\Roaming\\Bitcoin",
  "bitcoin_rpc_password": null,
  "bitcoin_rpc_url": "127.0.0.1:8332",
  "bitcoin_rpc_username": null,
  "chain": "mainnet",
  "commit_interval": 5000,
  "config": null,
  "config_dir": null,
  "cookie_file": "C:\\Users\\Administrator\\AppData\\Roaming\\Bitcoin\\.cookie",
  "data_dir": "C:\\Users\\Administrator\\AppData\\Roaming\\ord\\signet",
  "first_inscription_height": 767430,
  "height_limit": null,
  "hidden": [],
  "index": "C:\\Users\\Administrator\\AppData\\Roaming\\ord\\signet\\index.redb",
  "index_cache_size": 4284043264,
  "index_runes": false,
  "index_sats": false,
  "index_spent_sats": false,
  "index_transactions": false,
  "integration_test": false,
  "no_index_inscriptions": false,
  "server_password": null,
  "server_url": null,
  "server_username": null
}

**Comment by cryptoni9n** [comment] 2024-04-21 15:31
> > > 我`ord 0.18.2`在 Linux 上也一样：
> > > ```
> > > chain: testnet
> > > no_index_inscriptions: true
> > > index_runes: true
> > > index_cache_size: 8858365080
> > > ```
> > 
> > 
> > 请运行`ord --data-dir <DATA_DIR> settings`并将结果粘贴到此处。
> 
> 我在signet输出结果是这个： D:\ord\target\release> .\ord.exe --data-dir C:\Users\Administrator\AppData\Roaming\ord\signet settings { "bitcoin_data_dir": "C:\Users\Administrator\AppData\Roaming\Bitcoin", "bitcoin_rpc_password": null, "bitcoin_rpc_url": "127.0.0.1:8332", "bitcoin_rpc_username": null, "chain": "mainnet", "commit_interval": 5000, "config": null, "config_dir": null, "cookie_file": "C:\Users\Administrator\AppData\Roaming\Bitcoin\.cookie", "data_dir": "C:\Users\Administrator\AppData\Roaming\ord\signet", "first_inscription_height": 767430, "height_limit": null, "hidden": [], "index": "C:\Users\Administrator\AppData\Roaming\ord\signet\index.redb", "index_cache_size": 4284043264, "index_runes": false, "index_sats": false, "index_spent_sats": false, "index_transactions": false, "integration_test": false, "no_index_inscriptions": false, "server_password": null, "server_url": null, "server_username": null }

this is from signet, you need to get the ord settings for mainnet, so use that as your --data-dir instead.

**Closed** 2024-06-12 00:48 UTC

**Comment by xiaobinniu** [comment] 2024-09-22 09:59
index_cache_size ??
How big a value should I set? My server only has 16g of memory.
