### ISSUE TITLE
When etching a rune, batch requires a file even when using a delegate.  

### ISSUE THREAD

**Issue by cliobitcoinbank** [ordinals/ord#3445] opened 2024-04-02 08:32 UTC
When etching a rune, batch requires a file even when using a delegate.  I had thought this bug was fixed in previous versions but maybe have been reintroduced with runes?  Using delegates with runes icon inscriptions means we can save on fees by inscribing our images long before the halvening and the delegating to them later, this feature mostly works but may confuse some people trying to delegate in this way for runes.
Related:
https://github.com/ordinals/ord/pull/3027/files/7fc9271a5cf9190d3e20b7986932fab084869a67

**Comment by cryptoni9n** [comment] 2024-04-04 14:58
duplicate of #3396

**Closed** 2024-04-09 07:59 UTC
