### ISSUE TITLE
The ord running on testnet3 will pause at a certain block for a long time and cannot keep up with the actual block height

### ISSUE THREAD

**Issue by ArthurQiuys** [ordinals/ord#3965] opened 2024-09-23 18:00 UTC
Is there any way to speed up or solve this problem?

**Comment by rabbitprincess** [comment] 2024-09-24 00:25
I have same issue. it seems every ord stopped in testnet

**Comment by cryptoni9n** [comment] 2024-09-28 15:26
dupe of #3935

**Closed by cryptoni9n** 2024-09-28 15:26 UTC
