### ISSUE TITLE
Minting Off By 1 Error

### ISSUE THREAD

**Issue by owenstrevor** [ordinals/ord#3643] opened 2024-04-21 18:50 UTC
If a mint starts on block 40, ord will not let you mint until that block has already passed. Meaning the first block ord allows you to mint in is actually block 41.

**Comment by elder-rus** [comment] 2024-04-21 19:15
I think there must something to ignore errors, I tried to find it last days, I think it's in core of ord wallet

**Comment by 0xcruci** [comment] 2024-04-21 19:44
We identified the issue here:
https://github.com/ordinals/ord/blob/08bbf566502533217d7c5d24287e9f93b3bfc8a8/src/index/entry.rs#L66

It looks like the `height` might be the last confirmed block and is 1 behind. If that's the intent, then one fix would be to have the statement be: `if height < (start - 1)` or `if (height + 1) < start`

But perhaps there's a bug in `height` causing the off-by-one. Thanks!

**Comment by bFanek** [comment] 2024-04-21 19:48
this is fixed in this PR: https://github.com/ordinals/ord/pull/3645

**Comment by elder-rus** [comment] 2024-04-21 21:54
> If a mint starts on block 40, ord will not let you mint until that block has already passed. Meaning the first block ord allows you to mint in is actually block 41.

u can download source code, make fix for [ord/src/index/entry.rs](https://github.com/ordinals/ord/blob/08bbf566502533217d7c5d24287e9f93b3bfc8a8/src/index/entry.rs#L66) and just compile, then replace ur exe in ord folder

**Comment by casey** [comment] 2024-04-22 23:48
Fixed in #3659. Thank you for reporting!

**Closed** 2024-04-22 23:47 UTC
