### ISSUE TITLE
Ethcing: Batchfile must contain at least one inscription

### ISSUE THREAD

**Issue by pxr64** [ordinals/ord#3465] opened 2024-04-04 13:02 UTC
Etching does not work if i don't specify an inscription configuration

**Comment by cryptoni9n** [comment] 2024-04-04 14:58
duplicate of #3396

**Comment by raphjaph** [comment] 2024-04-22 19:35
At the moment you need to create an inscription but you can specify an empty one by doing: 
```
inscriptions:
  - 
```

**Closed by raphjaph** 2024-04-22 19:35 UTC
