### ISSUE TITLE
Programmable Audio - SharedArrayBuffer on Ordinals.com

### ISSUE THREAD

**Issue by owenstrevor** [ordinals/ord#3850] opened 2024-07-10 18:07 UTC
We're emulating the Nintendo NES 8-bit sound chip and the Texas Instruments TMS5220 speech synthesizer chip to make the sound effects for the Pizza Pets project.

We noticed that ordinals.com is not running in a cross origin isolated environment, so therefore we do not have access to the "SharedArrayBuffer" object which we would like to be able to use in order to have communication between audio worklets and the main thread, without having to go through the hassle of copying memory buffers back and forth between threads.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

I was wondering, would it be possible to set the necessary headers on your server to enable this?

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

cc @patrick99e99

Thanks so much!

**Comment by Trollfarmer** [comment] 2024-07-11 05:19
Did you try the service worker approach?

https://dev.to/stefnotch/enabling-coop-coep-without-touching-the-server-2d3n

**Comment by patrick99e99** [comment] 2024-07-14 04:55
> @owenstrevor Did you try the service worker approach?

We are trying to have as good of UX as possible, this means that we have an animated loading screen that displays immediately on page load, and proceeds to animate until all dependencies and resources have loaded.  The "service worker approach" involves having an abrupt page refresh which would result in a less than ideal user experience based off of how we are loading / preparing the application.

It would be ideal if we can just get the Bitcoin indexers to all offer cross origin isolated environments by setting these headers.

**Comment by casey** [comment] 2024-08-12 00:14
This seems reasonable to me. The only question I have is, it looks like these are more restrictive policies, is it possible that they could break any existing inscriptions?

**Comment by patrick99e99** [comment] 2024-08-12 03:49
> is it possible that they could break any existing inscriptions?

I can't see how, all these headers do is isolate content from other origins (and the result of this is unlocking features like the SharedArrayBuffer), which is already expected behavior as ordinals indexers do not allow any interaction with the outside world.

**Comment by casey** [comment] 2024-08-12 17:40
Okay, sounds reasonable to me. Feel free to open a PR! It would also be worth thinking about how to communicate this change to the various explorers, since to get cross-ecosystem support, other explorers would have to add this header as well.

**Comment by patrick99e99** [comment] 2024-08-12 23:42
> Feel free to open a PR!

https://github.com/ordinals/ord/pull/3898

**Comment by casey** [comment] 2024-08-13 17:05
Merged! I added a test, and changed the name of the flag to `--disable-cross-origin-isolation`. Thanks for the PR!

**Closed by casey** 2024-08-13 17:05 UTC
