### ISSUE TITLE
redb error when indexing (on master: 938b5cc)

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#1485] opened 2023-02-03 16:32 UTC
I started indexing, stopped it with CTRL-C and then started again.

```
thread 'main' panicked at 'internal error: entered unreachable code', /Users/raphael/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.12.1/src/tree_store/btree_mutator.rs:971:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: redb::tree_store::btree_mutator::MutateHelper<K,V>::delete_helper
   4: redb::tree_store::btree_mutator::MutateHelper<K,V>::delete_helper
   5: redb::tree_store::btree_mutator::MutateHelper<K,V>::delete_helper
   6: redb::tree_store::btree_mutator::MutateHelper<K,V>::delete_helper
   7: redb::tree_store::btree_mutator::MutateHelper<K,V>::delete_helper
   8: redb::tree_store::btree_mutator::MutateHelper<K,V>::delete
   9: redb::tree_store::btree::BtreeMut<K,V>::remove
  10: ord::index::updater::inscription_updater::InscriptionUpdater::index_transaction_inscriptions
  11: ord::index::updater::Updater::update_index
  12: ord::index::updater::Updater::update
  13: ord::subcommand::index::run
  14: ord::subcommand::Subcommand::run
  15: ord::main

```

**Comment by hantuzun** [comment] 2023-02-03 18:10
Duplicate of https://github.com/casey/ord/issues/1471

**Closed** 2023-08-31 20:46 UTC
