### ISSUE TITLE
Get signet.ordinals.com and testnet.ordinals.com back

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#2267] opened 2023-07-12 16:03 UTC
- also set up with Cloudlflare in between

**Comment by awa-labs** [comment] 2023-07-20 04:32
Still 'This site can’t be reached' for the two.

planing implement one locally...

**Comment by sanyo16** [comment] 2023-08-03 14:07
Hello, any idea when this will be fixed?

**Comment by cypherpork** [comment] 2023-08-04 14:03
Duplicate of #2227

**Closed** 2023-08-22 12:03 UTC
