### ISSUE TITLE
Provide a library for building web wallets

### ISSUE THREAD

**Issue by earthflower** [ordinals/ord#1621] opened 2023-02-09 09:42 UTC
Request you to provide cdylib version so that wasm builds can be made for library which facilities further distribution of ordinals

**Comment by earthgohan** [comment] 2023-02-09 22:54
I tried building ord for cdylib version
* Server crate with miso, tokio doesn't support wasm. * * Trying on seperating only wallet

**Comment by casey** [comment] 2023-08-31 19:43
Dupe of #1249.

**Closed by casey** 2023-08-31 19:43 UTC
