### ISSUE TITLE
Divide by zero error since block 840357

### ISSUE THREAD

**Issue by GiantDole** [ordinals/ord#3652] opened 2024-04-22 15:27 UTC
Ord will not sync any further than block 840357 and throws the attached error whenever I start the server.
<img width="1567" alt="Screenshot 2024-04-22 at 5 27 13 PM" src="https://github.com/ordinals/ord/assets/1206655/dbd899cc-69bd-47be-807c-524d969a80d3">

Does anyone experience the same error?

**Comment by robotlovecoffee** [comment] 2024-04-22 15:44
I got same error on my ubuntu node and cannot get back it, on my others nodes seems fine running 0.18.1

**Comment by veryordinally** [comment] 2024-04-22 16:09
Don't have this issue with 0.18.3

**Comment by t4t5** [comment] 2024-04-22 16:11
Ordiscan was affected by this running 0.18.1. Upgrading to 0.18.3 seems to have fixed it.

**Comment by utxo-detective** [comment] 2024-04-22 16:31
Ordinals wallet affected by this as well. Upgrading now

**Comment by cryptoni9n** [comment] 2024-04-22 21:58
Dupe of #3651

**Closed** 2024-04-22 22:00 UTC
