### ISSUE TITLE
Wallet GUI

### ISSUE THREAD

**Issue by cryptoquick** [ordinals/ord#1417] opened 2023-01-30 00:04 UTC
A basic GUI for all wallet commands would be really helpful for those who want to self-custody their inscriptions instead of having their friends hold 'em. But they're usually running their node on Umbrel or Embassy. So, it'd ideally have a web interface. See these guidelines here:
https://docs.start9.com/latest/developer-docs/packaging

Since it'd give access to a bitcoind wallet, and it'd be hosted on a URL, usually an onion address, it'd make sense to authenticate all requests, so, a password mechanism would need to be devised. Maybe just entering the fingerprint of the ord wallet could be enough, that would stay secret unless it's ever shared.

Ideally it would integrate into the preview somehow, and wallet inscriptions would list those that are yours.

**Comment by cryptoquick** [comment] 2023-01-30 00:11
I don't have an Umbrel, but I can package it up for Embassy once there's a UI. Ideally there'd also be a Dockerfile also, I think.

**Comment by raphjaph** [comment] 2023-02-06 14:00
Packing for node bundles is something we will probably do once we are in beta or later

**Comment by casey** [comment] 2023-02-07 23:29
I think we should let users package `ord` for different distros, and provide support on our end, but not manage those packages ourselves. This has been my strategy for [just](https://github.com/casey/just), where I quickly learned that packaging was very time consuming, even more so if you don't happen to use the OS that you're packaging for. Right now, Just will make changes that are needed to support packagers, but I don't own any of the packages myself.

**Comment by cryptoquick** [comment] 2023-02-08 23:59
Yes, but a web wallet GUI is needed for a remotely hosted version of ord, since both Embassy and Umbrel can't safely expose Bitcoin Core RPC ports.

**Comment by gnoblin** [comment] 2023-02-09 17:30
how do I do remotely hosted ord? thanks

**Comment by casey** [comment] 2023-08-30 21:04
Dupe of #1247.

**Closed by casey** 2023-08-30 21:04 UTC
