### ISSUE TITLE
Can we create multiple inscriptions within the same transaction?

### ISSUE THREAD

**Issue by jiedo** [ordinals/ord#1956] opened 2023-03-21 15:16 UTC
Currently we can only create 1 in the first input, are there plans to support multiple? @casey

I found 115 inputs here, each input has a inscription body: https://blockstream.info/tx/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc

**Comment by nammaki** [comment] 2023-03-21 23:34
Def would love for this feature to be supported 🚀

**Comment by veryordinally** [comment] 2023-03-24 17:24
Not supported right now, planned in #1298

**Comment by nammaki** [comment] 2023-03-26 18:03
After more searching, it looks like @casey calls this "bundles" and it's listed in the roadmap but seems like no work has been done yet, https://github.com/casey/ord/issues/1212, https://github.com/casey/ord/issues/1248, https://github.com/casey/ord/issues/876 🙏

**Comment by VincentDebug** [comment] 2023-04-03 10:57
https://github.com/VincentDebug/go-ord-tx-demo

Supports two types of batch inscriptions:

One commit transaction with multiple reveal transactions.
One commit transaction with a single reveal transaction.

**Comment by Crypt-vj** [comment] 2023-04-09 23:05
> https://github.com/VincentDebug/go-ord-tx-demo
> 
> Supports two types of batch inscriptions:
> 
> One commit transaction with multiple reveal transactions. One commit transaction with a single reveal transaction.

This is awesome. Could you plz add some documentation around usage in Readme?

**Comment by casey** [comment] 2023-08-31 20:17
Dupe of #876.

**Closed by casey** 2023-08-31 20:17 UTC
