### ISSUE TITLE
Panic while sending rune: input ... not found in wallet

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3439] opened 2024-04-01 22:44 UTC
Strange results from this sequence of commands. 

I checked my balance, sent out all of one token, then tried to send out all of the next token. Was told I only have 12 of it, but when I tried to send 12 of it I got a panic, and now my balance shows I have none of it.

Note that the address I am sending to is an address in the wallet I am sending from, if that matters.

```
$ ords3 balance
{
  "cardinal": 0,
  "ordinal": 1980,
  "runes": {
    "GREG": 30000,
    "GREG•GREG•GREG": 7535,
    "THESE•WILL•BE•WORTHLESS": 120
  },
  "runic": 70000,
  "total": 71980
}

$ ords3 send --fee-rate 1 tb1patp6wwevn5nmdg5fklnwf0uj2kz76qt3whntjysue62pmcsmx25s8hz74f 30000:GREG
error: insufficient `GREG` balance, only 3000 B in wallet

$ ords3 send --fee-rate 1 tb1patp6wwevn5nmdg5fklnwf0uj2kz76qt3whntjysue62pmcsmx25s8hz74f 3000:GREG
{
  "txid": "4ff7b61241137c7c2ec3d1109e7342e643a001ef6ae1bb79996feb0ca96feb96",
  "psbt": "cHNidP8BAP0bAQIAAAADCWHeA2vnb3IVuWAlOpBq7mBue4u/rI1LbDD3iTqrOowBAAAAAP////85tVFIlPjauJ0qdm7IIGd5zO/l8QhBdBY57GMSWph70AEAAAAA/////5SmAg0rP6yPL5oQ05h2T2ToUAaCdIDvkobcDsIV7yD6AQAAAAD/////BAAAAAAAAAAADGpdCQC2wwsTsOoBAhAnAAAAAAAAIlEgmcYzHXxa0iaVpZdyUZdD7hw1p2FGzs7fuRHUGAzr+qEQJwAAAAAAACJRIOrDpzssnSe2oom35uS/klWF7QFxdea5EhzOlB3iGzKpwiUAAAAAAAAiUSCt9TzwMnArnva5I9WVj1iODepI/LTYDzfzh21hhC8qCAAAAAAAAQErECcAAAAAAAAiUSDZSZ426ff7RiksnwbvVhkK03CX6My/fFIqmNy0EpRFuwEIQgFApFHSSlHKhUd5uNmVENUZQ4ZN2NV/shjnf2WLhoRzzs+kqCj8FuP/jCsbl/DERoeA+DWn61wJmKsPfn3qkimnYQABASsQJwAAAAAAACJRIIevgGs+a0Je49d3Ljm3mmIHJfzKEFiDc1KJl0tB4I8QAQhCAUDzXgPQR0J/Sz9XQNxdzEbZMuM4/qtG/l1emLfRfqvz2Nm/XOFSROar/h/rQxzxJrKSUUuf4L+L1l9ZSyMkM7NbAAEBKxAnAAAAAAAAIlEgBJiAnwKOovBMqqooY+GajxDcyY3jd9wPhcTb77qh7G4BCEIBQFJnmKuIBu59Yqv6hpJ1LdOyXaEUbdGjXCqg18lf6G1Xk2ZpkSKwzth+THUQWCL6UbMhnzNNdsVzjekrXQAQkO4AAAEFICxbrSCqFB0JQSWt4d7Bt9udxOdCTA3e48FePYK8GLcdIQcsW60gqhQdCUElreHewbfbncTnQkwN3uPBXj2CvBi3HRkAq7vwdlYAAIABAACAAAAAgAEAAACNAAAAAAEFIOSHjrC0B5r+6gPl5A4xUA+KPONkWqCDhtdNGqkJ2JK0IQfkh46wtAea/uoD5eQOMVAPijzjZFqgg4bXTRqpCdiStBkAq7vwdlYAAIABAACAAAAAgAAAAAAHAAAAAAEFIPyM21TERTim4R3OikzHcqPOX3kTlwyYzGC7r2S62Gb4IQf8jNtUxEU4puEdzopMx3Kjzl95E5cMmMxgu69kuthm+BkAq7vwdlYAAIABAACAAAAAgAEAAACOAAAAAA==",
  "outgoing": "3000:GREG",
  "fee": 334
}

$ ords3 send --fee-rate 1 tb1patp6wwevn5nmdg5fklnwf0uj2kz76qt3whntjysue62pmcsmx25s8hz74f 120:THESEWILLBEWORTHLESS
error: insufficient `THESEWILLBEWORTHLESS` balance, only 12 ø in wallet

$ ords3 send --fee-rate 1 tb1patp6wwevn5nmdg5fklnwf0uj2kz76qt3whntjysue62pmcsmx25s8hz74f 12:THESEWILLBEWORTHLESS
thread 'main' panicked at src/subcommand/wallet/send.rs:116:9:
input de3b5432fcaa0ab45d961d5d5729cf1379f5dc5b9ae6cd4c0bd77bbafa54571e:3 not found in utxos
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ ords3 balance
{
  "cardinal": 0,
  "ordinal": 1980,
  "runes": {
    "GREG•GREG•GREG": 7535
  },
  "runic": 20000,
  "total": 21980
}
```

**Comment by JoeyKhd** [comment] 2024-04-02 00:23
duplicate of https://github.com/ordinals/ord/issues/3406

**Closed** 2024-04-02 00:39 UTC
