### ISSUE TITLE
Provide a way to burn an inscription

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2597] opened 2023-10-26 16:41 UTC
Ord client should provide an official way to burn an inscription. This way, a parent inscription can be burned after creating a collection, and we can show a "burned" label on the new collection page #2561.

cc @veryordinally

**Comment by DrJingLee** [comment] 2023-10-26 17:17
Something like When inscription has an ownwr address of 1BitcoinEaterAddressDontSendf59kuE

then give it a tag of “burned” ?

**Comment by elocremarc** [comment] 2023-10-26 21:41
I think burning to an unspendable output would be ideal. Then you can still sign for the inscription. It would allow for POAPs and Soul Bound Tokens.

**Comment by raphjaph** [comment] 2023-10-31 18:46
Ideally we would want to burn to an `OP_RETURN` because this way Bitcoin can prune the output.

**Comment by casey** [comment] 2024-02-12 19:43
Dupe of https://github.com/ordinals/ord/issues/1333.

**Closed by casey** 2024-02-12 19:43 UTC
