### ISSUE TITLE
Is it possible to provide a complete verified index.redb download？

### ISSUE THREAD

**Issue by kirito41dd** [ordinals/ord#1914] opened 2023-03-11 05:20 UTC
Indexing is too slow, I've run it for 2 days and it's not complete.

```
[indexing blocks] █████████████████████████████████████████████████████████████████████████████████████████████████████░░ 770508/780161
```

**Comment by gmart7t2** [comment] 2023-03-11 12:50
I don't know what "verified" would mean but I have been providing index.redb files for download for the last 3 weeks or so. Lots of satisfied downloaders, no complaints. 

The site doesn't have a certificate (or even a domain name) so you will get a warning.  But here it is:

[index.redb files](https://45.128.27.75/)

The indexes are up to date as of block 780000 from 2 days ago. There are 2 versions, one with and one without the --index-sats flag.

**Comment by kirito41dd** [comment] 2023-03-11 13:56
@gmart7t2 thank you, i want try it, but the download speed is 20b/s

**Comment by Psifour** [comment] 2023-03-19 19:12
There are no "verified" download methods available yet, but users (like @gmart7t2) have provided their own index files publicly. A method to validate downloaded indexes has been considered by a few different developers within the community, but I have yet to see anyone follow through on that.

**Comment by EscVector** [comment] 2023-04-19 01:13
I'm working this because I find waiting very annoying.  Will comprise container based core and ord run on 30 minute cycle that dumps to object storage.  Will make the image available, quick simple, secure.  Goal is to have a sync that is never more than 3 or 4 blocks behind so will complete in less than 1 hour.  Will have no-sat and sat indexes.   Verification is tricker.  At the very lest, a "trusted" file will be available.  #TrustButVerify

**Comment by casey** [comment] 2023-09-05 20:03
Duplicate of #1701.

**Closed by casey** 2023-09-05 20:03 UTC
