### ISSUE TITLE
Indexing blocks serious error cannot be resolved

### ISSUE THREAD

**Issue by a62316004** [ordinals/ord#2070] opened 2023-05-07 09:20 UTC
[2023-05-07T09:26:28Z ERROR ord::index::updater] Couldn't receive txs Failed to fetch raw transaction: code -5 message No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
error: failed to get transaction for 093f6718db6d659385f7c43fcccee307b9f3a9b4bbf786fb7559f03e05e1da70
![image](https://user-images.githubusercontent.com/78856448/236668942-f6ea9e16-80f8-40f5-9ecb-052cf8242be7.png)

The block is normal, the wallet is normal, but it has been stuck here and failed

**Comment by a62316004** [comment] 2023-05-07 09:30
Adding txindex=1 also prompts an error

**Comment by a62316004** [comment] 2023-05-07 09:33
ERROR: FindTx: Deserialize or I/O error - ReadCompactSize(): size too large: iostream error

**Comment by so7ow** [comment] 2023-05-13 16:46
After you add txindex=1 you need to wait for the indexing to complete. You can check indexing status with `bitcoin-cli getindexinfo`. Look for the current block height and synced=true.

**Comment by casey** [comment] 2023-08-31 18:13
Closing, since there doesn't appear to a be instructions to reproduce.

**Closed by casey** 2023-08-31 18:13 UTC
