### ISSUE TITLE
Bad Inscriptions

### ISSUE THREAD

**Issue by rayonx** [ordinals/ord#1965] opened 2023-03-23 15:46 UTC
On signet: these are some bad inscriptions that the explorer fails to display properly

example `http://0.0.0.0/inscription/283d3d842f7314ed55331322a4c60af45e25f4f75a73711dd1324fc0e8d15b70i0`
would respond with `Internal Server Error`

key-value pair of inscription_id and inscription_number

> `{'283d3d842f7314ed55331322a4c60af45e25f4f75a73711dd1324fc0e8d15b70i0': 0, '83dc96d5274d8b358cdbaa4aa868c263df2fde459c9848a109aa7cbfcc8689e0i0': 213, '0a44b987a828787489bd751cdeacd02369370af682cd443bfcfdc75d8bb6d563i0': 221, '5bff5d6619b3634619de844169a3a3cfd9bae844cadfb9d2fec13b3715014157i0': 230, 'df8116e1a4432058edcf6d0ddcfb21af8b00533c1c92acfb2b9b543db55d5d6ci0': 661, '59947feed403acf653e94b9dd20a0c8468752aa97117f512891bd675ea9c4073i0': 662, '2de989aa33532279105efa75463731f4264c7c4aec29f47eddc9a28475cfa874i0': 663, 'da2f63882a8d36786fe3357d3a37911fe1e76ff94a35ee2503457a78df6953b6i0': 667, '8de0d1a3f8557f2a55f0350d6e465d886c65b7f3cb003d7e8a3c309ce6bdff7fi0': 668, '3eb38e8392a7eb95765f891e3eb18252c9d1d30441bf2abea17a406d028689bei0': 670, 'c59aebd7fe38d5c0f7dd48888c10d39b2944dfbfd5b81fb181a4e3f28e6fa568i0': 685, 'f6f11a30282e6ca6c4be3ae9050b1ccc150f76a1c2b2ea37788e339c4767c801i0': 686, '18e3fa88f338aa2d38b33b29dce52fd4fca034577e9e84a3023b57b9575b560ai0': 688, '0edb519d578eb1baa5ab2d621d7440cfd33f7f251f6451962c47a7bcc6346440i0': 689, '5a6791dd77f59846e5b5789d28229f6afa231d21f0748ed23cc2ae4c98b1817ai0': 690, '227d81cf3a481d66e0f9e4cfc532a94286d524d907ba41a9798dd38c72d5387di0': 694, '88ad39f3c5fb8a8eb8b1af8f977ab0ddaf4c2263e21a4e0df4e00abd229bb0abi0': 695, '37ee3cb331193618da6855083d2a43991bd3305fd2b963cff45e04d05945c587i0': 696, '840d577912b15cb6cd7cbc55a784317257363495ae4a9491048c1f7ad2335190i0': 701, '0f352a15c3b84f965a36c2f3f3b26f94cabb87da21dc02bcbf57fd8477fa2353i0': 713, '07b9b3f0a5317098166178471f4f81132c1cdaac6b01aa363253f3cfd34eb548i0': 744, '0f65c3b5fd3c285ee7290bcd6b9c5541cecf8b2974ccaf66afca136c000ef2dai0': 948}`

Problem persists on the mainnet as well. 

mainnet example:

> Inscription #6928
> /inscription/ebfc364d43e6f921bc9aff3831340e1b06f8c813cb6fbb8a6a54aa26a8f80497i0

**Comment by nammaki** [comment] 2023-03-23 18:17
I searched issues and there seems to be many related issues 🤔 https://github.com/casey/ord/issues/1841, https://github.com/casey/ord/issues/1872, https://github.com/casey/ord/issues/1902, https://github.com/casey/ord/issues/1957, https://github.com/casey/ord/issues/1964

**Comment by veryordinally** [comment] 2023-03-24 17:15
Duplicate of #1841 - inscriptions spent as miner fees not displayed correctly.

**Closed as completed** 2023-03-24 17:24 UTC
