### ISSUE TITLE
Inconsistent inscription numbers and sat bindings

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#2869] opened 2023-12-16 17:52 UTC
I recently noticed an issue with inscription numbers in ord 0.12.x

I have been maintaining ord 0.12.x indexes on a few different servers and noticed that some inscriptions have different numbers on different servers. 

Party if the problem was that the "stuttering curse" fix didn't bump the database schema number, so that resulted in the indexes getting out of step with each other, and that is understandable. 

What I don't understand is that one of the indexes has inscriptions from 2 different reveal txs intertwined with each other. 

I see:

* Inscription numbers -272646 to -272657 are e1c3fb9ef625efc357925b4030d1f6b112317e5ddcc1ade78a9fc9f8766fcb37i0-11
* Inscription numbers -272658  to -272669 are 0ccab9ff6c9579b2d554330845e429c531943a964ebbd95e80422943938e0ba0i0-11
* Inscription numbers -272670 to -272869 are e1c3fb9ef625efc357925b4030d1f6b112317e5ddcc1ade78a9fc9f8766fcb37i12-211
* Inscription numbers -272870 to -273069 are 0ccab9ff6c9579b2d554330845e429c531943a964ebbd95e80422943938e0ba0i12-211

So that's:
* the first 12 inscriptions from tx1
* then the first 12 inscriptions from tx2
* then the remaining from tx1
* then the remaining from tx2

How could that have happened? Aren't the reveal txs processed sequentially?

Both txs spend commitments from the same shared patent tx.

All the inscriptions in both txs use the pointer tag, even for the first inscription

Both txs have the same parent inscription, so tx2's first input is an output of tx1.

Both txs are confirmed in the same block. 

The same thing happens twice more, for 2 more pairs of reveal txs, where the first 12 inscriptions for each tx appear before the remaining txs from both tx.

Maybe this was already found and fixed. I'm not sure. Maybe it is still an issue that happens intermittently.

**Comment by gmart7t2** [comment] 2023-12-16 21:59
The commit that changed this behavior is commit 6f64528f210e2e7e736ff611926bcda4953f24f8.

In 0.12.0 through 0.12.2, the first 12 inscriptions of each reveal tx get inscription numbers before the rest of the inscriptions get assigned numbers. 

In 0.12.3 all the inscriptions in each reveal tx get consecutive inscription numbers.

**Comment by casey** [comment] 2023-12-17 08:46
Does this only affect negative inscription numbers? If so, then it seems like this is okay. Negative inscription numbers are not guaranteed to be stable, and the 0.12.3 numbering seems better, since they're assigned consecutively.

**Comment by gmart7t2** [comment] 2023-12-17 10:11
> Does this only affect negative inscription numbers?

No. It also affects the location/binding of the cursed inscriptions. All but the first 12 inscriptions were spent as fees in 0.12.0 through 0.12.2 but in 0.12.3 none of them were spent as fees.

**Comment by casey** [comment] 2024-01-02 00:56
I double-checked everything, and it looks like everything is working correctly. The inscriptions made in both transactions have sequential, continuous transaction numbers, and the current location of each is the first sat of a different output, which looks like it's what the inscriber intended.

I'm not sure why this changed in old versions. I have a feeling that Raph and I were looking at something in the inscription updater, realized that there was a bug, and fixed it and merged the fix in the PR for whatever we were working on.

So I'm going to go ahead and close this, since it seems to be working as intended now.

Thanks so much for reporting this! Bad that we missed it, but good that it seems to be working.

**Closed by casey** 2024-01-02 00:56 UTC
