### ISSUE TITLE
Etch runes without having to inscribe anything using the batch command

### ISSUE THREAD

**Issue by hwnprsd** [ordinals/ord#3490] opened 2024-04-09 07:49 UTC
Currently we have to inscribe something in order to etch a rune using the `ord wallet batch` command. Is this a requirement?

**Comment by 0xprames** [comment] 2024-04-09 08:46
this issue seems to be a duplicate of https://github.com/ordinals/ord/issues/3396

in #3396 they link this as to be PR out for this: https://github.com/ordinals/ord/pull/3451

**Closed** 2024-04-09 12:41 UTC
